<form method="post" action="{{ route('report.audit_cancell') }}">
    @csrf
    <div class="container-fluid">
        <div class="box no-border mb-2">
            <div class="box-header p-0">
                <div class="d-flex align-items-center justify-content-between">
                    <h4 class="box-title">Cancelled Bills</h4>
                </div>
            </div>
            <div class="box-body px-0 ">
                <div class="row">
                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="fromdate">From <span class="text-danger">*</span></label>
                            <input type="date" class="form-control" id="fromdate" name="fromdate" value="{{ date('Y-m-d') }}" required>
                        </div>
                    </div>
                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="todate">To <span class="text-danger">*</span></label>
                            <input type="date" class="form-control" id="todate" name="todate" value="{{ date('Y-m-d') }}" required>
                        </div>
                    </div>
                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="branch">Branch<span class="text-danger">*</span></label>
                            <select class="form-control" id="branch" name="branch" required>
                                <option value="">All</option>
                                @foreach ($branches as $branch)
                                    <option value="{{ $branch['id'] }}">{{ $branch['name'] }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="billedby">Billed By</label>
                            <select class="form-control" id="billedby" name="billedby">
                                <option value="">All</option>
                                @foreach ($billStaffs as $billStaff)
                                    <option value="{{ $billStaff->id }}">{{ str_replace('<br>', ' ', $billStaff->name) }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="generatedby">Bill Generated By</label>
                            <select class="form-control" id="generatedby" name="generatedby">
                                <option value="">All</option>
                                @foreach ($billStaffs as $billStaff)
                                    <option value="{{ $billStaff->id }}">{{ str_replace('<br>', ' ', $billStaff->name) }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer p-3 px-0 text-end " style="border-radius: 0px;">
                <button type="submit" class="btn btn-success" id="searchauditcancelBillbtn">
                    <i class="fa fa-search"></i> Search
                </button>
            </div>
        </div>
    </div>
    <div class="auditcancelBilldiv container" style="display: none;">
        <div class="table-responsive" style="width: 100%; overflow-x: auto;">
            <table class="table table-bordered table-hover table-striped mb-0 data-table text-center" id="auditcancelBillTable" width="100%">
                <thead class="bg-primary-light">
                    <tr>
                        <th>#</th>
                        <th>Date</th>
                        <th>Patient ID</th>
                        <th>Patient Name</th>
                        <th>Bill No</th>
                        <th>Total</th>
                        <th>Discount</th>
                        <th>Tax</th>
                        <th>Net Amount</th>
                        <th>Cash</th>
                        <th>GPay</th>
                        <th>Card</th>
                        <th>Total Paid</th>
                        <th>Balance Given</th>
                        <th>Outstanding</th>
                        <th>Created By</th>
                        <th>Updated By</th>
                        <th>Deleted By</th>
                        <th>Reason</th>
                    </tr>
                </thead>
                <tfoot class="bg-light-gray">
                    <tr>
                        <th colspan="5">Total</th>
                        <th class="total"></th>
                        <th class="discount"></th>
                        <th class="tax"></th>
                        <th class="netAmount"></th>
                        <th class="cash"></th>
                        <th class="gpay"></th>
                        <th class="card"></th>
                        <th class="totalPaid"></th>
                        <th class="balanceGiven"></th>
                        <th class="outstanding"></th>
                        <th colspan="4"></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</form>
<script type="text/javascript">
    var table;
    jQuery(function($) {
        var clinicBasicDetails = @json($clinicBasicDetails);

        $('#searchauditcancelBillbtn').click(function(e) {
            e.preventDefault(); // Prevent form submission

            var form = $(this).closest('form');
            var url = form.attr('action');
            var formData = form.serialize();

            // Destroy existing DataTable if initialized
            if ($.fn.DataTable.isDataTable("#auditcancelBillTable")) {
                $('#auditcancelBillTable').DataTable().destroy();
            }

            // Initialize DataTable
            $('#auditcancelBillTable').DataTable({
                processing: true,
                serverSide: true,
                searching: false,
                ordering: false,
                ajax: {
                    url: url,
                    type: 'POST',
                    data: formData,
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                },
                columns: [
                    {data: 'DT_RowIndex',
                        name: 'DT_RowIndex',
                        orderable: false,
                        searchable: false},
                    { data: 'billDate', name: 'billDate' },
                    { data: 'patient_id', name: 'patient_id' },
                    { data: 'patientName', name: 'patientName' },
                    { data: 'bill_id', name: 'bill_id' },
                    { data: 'total', name: 'total' },
                    { data: 'discount', name: 'discount' },
                    { data: 'tax', name: 'tax' },
                    { data: 'netAmount', name: 'netAmount' },
                    { data: 'cash', name: 'cash' },
                    { data: 'gpay', name: 'gpay' },
                    { data: 'card', name: 'card' },
                    { data: 'totalPaid', name: 'totalPaid' },
                    { data: 'balanceGiven', name: 'balanceGiven' },
                    { data: 'outstanding', name: 'outstanding' },
                    { data: 'createdBy', name: 'createdBy' },
                    { data: 'updatedBy', name: 'updatedBy' },
                    { data: 'deletedBy', name: 'deletedBy' },
                    { data: 'bill_delete_reason', name: 'bill_delete_reason' }
                ],
                dom: 'Bfrtlp',
                lengthMenu: [
                    [10, 25, 50, -1],
                    [10, 25, 50, 'All']
                ],
                buttons: [
                    {
                        extend: 'print',
                        text: 'Print',
                        title: clinicBasicDetails.clinic_name,
                        messageTop: 'Collection Report',
                        orientation: 'landscape',
                        pageSize: 'A3',
                        footer: true,
                        filename: 'Collection Report',
                        exportOptions: {
                            columns: ':visible'
                        },
                        customize: function (win) {
                            $(win.document.body).css('font-size', '10pt');
                            $(win.document.body).find('table').addClass('compact').css('font-size', 'inherit');
                        }
                    },
                    {
                        extend: 'excelHtml5',
                        text: 'Excel',
                        title: clinicBasicDetails.clinic_name,
                        messageTop: 'Collection Report',
                        footer: true,
                        filename: 'Collection Report',
                        exportOptions: {
                            columns: ':visible'
                        }
                    },
                    {
                        extend: 'pdfHtml5',
                        text: 'PDF',
                        title: clinicBasicDetails.clinic_name,
                        messageTop: 'Collection Report',
                        orientation: 'landscape',
                        pageSize: 'A3',
                        exportOptions: {
                            columns: ':visible'
                        },
                        footer: true,
                        filename: 'Collection Report',
                        customize: function (doc) {
                            doc.defaultStyle.fontSize = 10;
                            doc.styles.tableHeader.fontSize = 10;
                        }
                    }
                ],
                footerCallback: function (row, data, start, end, display) {
                    var api = this.api();
                    var columnsToSum = [6, 7, 8, 9, 10, 11, 12, 13, 14, 15];
                    columnsToSum.forEach(function (index) {
                        var total = api.column(index).data().reduce(function (a, b) {
                            return parseFloat(a) + parseFloat(b);
                        }, 0);
                        $(api.column(index).footer()).html(total.toFixed(2));
                    });
                },
                drawCallback: function () {
                    $('.auditcancelBilldiv').show();
                }
            });
        });
    });
</script>

