<form method="post" action="{{ route('report.collection') }}">
    @csrf
    <div class="container-fluid">
        <div class="box no-border mb-2">
            <div class="box-header p-0">
                <div class="d-flex align-items-center justify-content-between">
                    <h4 class="box-title ">
                        Cancelled Bills
                    </h4>
                </div>
            </div>
            <div class="box-body px-0 ">

                <div class="row">
                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="fromdate">From <span class="text-danger">
                                    *</span></label>
                            <input type="date" class="form-control" id="fromdate" name="fromdate"
                                value="<?php echo date('Y-m-d'); ?>" required>
                        </div>
                    </div>

                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="todate">To <span class="text-danger">
                                    *</span></label>
                            <input type="date" class="form-control" id="todate" name="todate"
                                value="<?php echo date('Y-m-d'); ?>" required>
                        </div>
                    </div>
                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="branch">Branch<span class="text-danger">
                            *</span></label></label>
                            <select class="form-control " type="text" id="branch" name="branch" required>
                                <option value="">All</option>
                                @foreach ($branches as $branch)
                                    <option value="{{ $branch['id'] }}"> {{ $branch['name'] }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="billedby">Billed By</label>
                            <select class="form-control " type="text" id="billedby" name="billedby">
                                <option value="">All</option>
                                @foreach ($billStaffs as $billStaff)
                                    <option value="{{ $billStaff->id }}">
                                        {{ str_replace('<br>', ' ', $billStaff->name) }}
                                    </option>
                                @endforeach

                            </select>
                        </div>
                    </div>

                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="generatedby">Bill Generated By</label>
                            <select class="form-control " type="text" id="generatedby" name="generatedby">
                                <option value="">All</option>
                                @foreach ($billStaffs as $billStaff)
                                    <option value="{{ $billStaff->id }}">
                                        {{ str_replace('<br>', ' ', $billStaff->name) }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                </div>

            </div>
            <div class="box-footer p-3 px-0 text-end " style="border-radius: 0px;">
                <button type="submit" class="btn btn-success" id="searchauditcancelBillbtn">
                    <i class="fa fa-search"></i> Search
                </button>
            </div>
        </div>
    </div>
    <div class="auditcancelBilldiv container" style="display: none;">
        <div class="table-responsive" style=" width: 100%;
    overflow-x: auto;">
            <table class="table table-bordered table-hover table-striped mb-0 data-table text-center"
                id="auditcancelBillTable" width="100%">
                <thead class="bg-primary-light">
                    <tr>
                        <th>#</th>
                        <th>Date</th>
                        <th>Patient ID</th>
                        <th>Bill No</th>
                        <th>Bill Type</th>
                        <th>Total</th>
                        <th>Discount</th>
                        <th>Tax</th>
                        <th>Net</th>
                        <th>Cash</th>
                        <th>Gpay</th>
                        <th>Card</th>
                        <th>Total Paid</th>
                        <th>Balance Given</th>
                        <th>Outstanding</th>
                        <th>Cancelled By</th>
                        <th>Reason</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
                <tfoot>
                    <tr class="bt-3 border-primary">
                        {{-- <th colspan="7">Total:</th> --}}
                        <th colspan="5"></th>
                        <th>Total:</th>
                        <th id="total-sum"></th>
                        <th id="total-dis"></th>
                        <th id="total-tax"></th>
                        <th id="total-net"></th>
                        <th id="total-cash"></th>
                        <th id="total-gpay"></th>
                        <th id="total-card"></th>
                        <th id="total-paid"></th>
                        <th id="total-balance"></th>
                        <th id="total-due"></th>
                        <th colspan="2"></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</form>
<script type="text/javascript">
    var table;
    jQuery(function($) {
        var clinicBasicDetails = @json($clinicBasicDetails);

        $('#searchauditcancelBillbtn').click(function(e) {
            e.preventDefault(); // Prevent form submission

            $('.auditcancelBilldiv').show();
        });

    });
</script>
