<form method="post" action="{{ route('report.collection')}}">
    @csrf
    <div class="box no-border mb-2">
        <div class="box-header p-0">
            <div class="d-flex align-items-center justify-content-between">
                <h4 class="box-title ">
                    Collection Report
                </h4>

                <button type='button'
                    class='waves-effect waves-light btn btn-circle btn-secondary btn-treatment-pdf-generate btn-xs mt-0 mb-2'
                    title='Download & Print Treatment Summary'><i class='fa fa-download'></i></button>
            </div>
        </div>
        <div class="box-body px-0 ">
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group">
                        <label class="form-label" for="fromdate">From <span class="text-danger">
                                *</span></label>
                        <input type="date" class="form-control" id="fromdate" name="fromdate"
                            value="<?php echo date('Y-m-d'); ?>" required>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label class="form-label" for="todate">To <span class="text-danger">
                                *</span></label>
                        <input type="date" class="form-control" id="todate" name="todate" value="<?php echo date('Y-m-d'); ?>"
                            required>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label class="form-label" for="branch">Branch</label>
                        <select class="form-control " type="text" id="branch" name="branch">
                            <option value="">All</option>
                            @foreach ($branches as $branch)
                                <option value="{{ $branch['id'] }}"> {{ $branch['name'] }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label class="form-label" for="billedby">Billed By</label>
                        <select class="form-control " type="text" id="billedby" name="billedby">
                            <option value="">All</option>
                            @foreach ($billStaffs as $billStaff)
                                <option value="{{$billStaff->id}}"> {{ str_replace("<br>", " ", $billStaff->name) }}</option>
                            @endforeach
                            
                        </select>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label class="form-label" for="generatedby">Bill Generated By</label>
                        <select class="form-control " type="text" id="generatedby" name="generatedby">
                            <option value="">All</option>
                            @foreach ($billStaffs as $billStaff)
                                <option value="{{$billStaff->id}}"> {{ str_replace("<br>", " ",$billStaff->name) }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <!-- <div class="col-md-2">
                    <div class="form-group">
                        <label class="form-label" for="discount">Discount</label>
                        <select class="form-control " type="text" id="discount" name="discount">
                            <option value="">All</option>
                            <option value="1">Admin</option>
                        </select>
                    </div>
                </div> -->

                <div class="col-md-2">
                    <div class="form-group">
                        <label class="form-label" for="outstanding">Outstanding</label>
                        <select class="form-control " type="text" id="outstanding" name="outstanding">
                            <option value="">All</option>
                            @foreach ($billStaffs as $billStaff)
                                <option value="{{$billStaff->id}}"> {{ str_replace("<br>", " ",$billStaff->name) }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label class="form-label" for="combooffer">Combo Offer</label>
                        <select class="form-control " type="text" id="combooffer" name="combooffer">
                            <option value="">All</option>
                            @foreach ($comboOffers as $comboOffer)
                                <option value="{{$comboOffer->id}}"> {{ $comboOffer->treatments->pluck('treat_name')->implode(', ') }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <label class="form-label" for="registration">Registration</label>
                        <select class="form-control " type="text" id="registration" name="registration">
                            <option value="">All</option>
                            @foreach ($billStaffs as $billStaff)
                                <option value="{{$billStaff->id}}"> {{ str_replace("<br>", " ",$billStaff->name) }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-footer p-3 px-0 text-end bb-1" style="border-radius: 0px;">
            <button type="submit" class="btn btn-success" id="searchcollectionbtn">
                <i class="fa fa-search"></i> Search
            </button>
        </div>
    </div>
    <div class="collectiondiv" style="display: none">
        <div class="table-responsive">
                <table class="table table-bordered table-hover table-striped mb-0 data-table text-center" id="collectionTable" width="100%">
                    <thead class="bg-primary-light">
                        <tr>
                            <th >#</th>
                            <th>Date</th>
                            <th>Patient ID</th>
                            <th>Patient Name</th>
                            <th>Branch</th>
                            <th>Visit</th>
                            <th>Total</th>
                            <th>Discount</th>
                            <th>Tax</th>
                            <th>Net</th>
                            <th>Cash</th>
                            <th>Gpay</th>
                            <th>Card</th>
                            <th>Total Paid</th>
                            <th>Balance Given</th>
                            <th>Outstanding</th>
                            <th>Created By</th>
                            <th>Updated By</th>
                        </tr>
                    </thead>
                    <tbody>
                       
                    </tbody>
                </table>
        </div>
    </div>
</form>
<script type="text/javascript">
    var table;
    jQuery(function($) {
    
    // Handle the search button click
    $('#searchcollectionbtn').click(function() {
        if ($.fn.DataTable.isDataTable(".data-table")) {
        // Destroy existing DataTable instance
        $(".data-table").DataTable().destroy();
    }
        $('.collectiondiv').show(); 
        table = $('#collectionTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: {
            url: "{{ route('report.collection') }}",
            type: 'POST',
            data: function(d) {
                d._token = $('input[name="_token"]').val();
                d.fromdate = $('#fromdate').val();
                d.todate = $('#todate').val();
                d.branch = $('#branch').val();
                d.billedby = $('#billedby').val();
                d.generatedby = $('#generatedby').val();
                d.outstanding = $('#outstanding').val();
                d.combooffer = $('#combooffer').val();
                d.registration = $('#registration').val();
            },
            dataSrc: function (json) {
                console.log('Response Data:', json); // Log response data
                return json.data; // Return the data part of the response
            }
        },
        columns: [
            { data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false },
            { data: 'billDate', name: 'billDate' },
            { data: 'patientId', name: 'patientId' },
            { data: 'patientName', name: 'patientName' },
            { data: 'branch', name: 'branch' },
            { data: 'visitCount', name: 'visitCount' },
            { data: 'total', name: 'total' },
            { data: 'discount', name: 'discount' },
            { data: 'tax', name: 'tax' },
            { data: 'netAmount', name: 'netAmount' },
            { data: 'cash', name: 'cash' },
            { data: 'gpay', name: 'gpay' },
            { data: 'card', name: 'card' },
            { data: 'totalPaid', name: 'totalPaid' },
            { data: 'balanceGiven', name: 'balanceGiven' },
            { data: 'outstanding', name: 'outstanding' },
            { data: 'createdBy', name: 'createdBy' },
            { data: 'updatedBy', name: 'updatedBy' }
        ]
    }); // Reload the DataTable with new data
        });
});

</script>