<form method="post" action="{{ route('report.collection') }}">
    @csrf
    <div class="container-fluid">
        <div class="box no-border mb-2">
            <div class="box-header p-0">
                <div class="d-flex align-items-center justify-content-between">
                    <h4 class="box-title ">
                        Collection Report
                    </h4>
                </div>
            </div>
            <div class="box-body px-0 ">

                <div class="row">
                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="fromdate">From <span class="text-danger">
                                    *</span></label>
                            <input type="date" class="form-control" id="fromdate" name="fromdate"
                                value="<?php echo date('Y-m-d'); ?>" required>
                        </div>
                    </div>

                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="todate">To <span class="text-danger">
                                    *</span></label>
                            <input type="date" class="form-control" id="todate" name="todate"
                                value="<?php echo date('Y-m-d'); ?>" required>
                        </div>
                    </div>
                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="branch">Branch</label>
                            <select class="form-control " type="text" id="branch" name="branch">
                                <option value="">All</option>
                                @foreach ($branches as $branch)
                                    <option value="{{ $branch['id'] }}"> {{ $branch['name'] }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="billedby">Billed By</label>
                            <select class="form-control " type="text" id="billedby" name="billedby">
                                <option value="">All</option>
                                @foreach ($billStaffs as $billStaff)
                                    <option value="{{ $billStaff->id }}">
                                        {{ str_replace('<br>', ' ', $billStaff->name) }}
                                    </option>
                                @endforeach

                            </select>
                        </div>
                    </div>

                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="generatedby">Bill Generated By</label>
                            <select class="form-control " type="text" id="generatedby" name="generatedby">
                                <option value="">All</option>
                                @foreach ($billStaffs as $billStaff)
                                    <option value="{{ $billStaff->id }}">
                                        {{ str_replace('<br>', ' ', $billStaff->name) }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <!-- <div class="col-md-3 col-lg-2">
                    <div class="form-group">
                        <label class="form-label" for="discount">Discount</label>
                        <select class="form-control " type="text" id="discount" name="discount">
                            <option value="">All</option>
                            <option value="1">Admin</option>
                        </select>
                    </div>
                </div> -->

                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="outstanding">Outstanding</label>
                            <select class="form-control " type="text" id="outstanding" name="outstanding">
                                <option value="">All</option>
                                @foreach ($billStaffs as $billStaff)
                                    <option value="{{ $billStaff->id }}">
                                        {{ str_replace('<br>', ' ', $billStaff->name) }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="combooffer">Combo Offer</label>
                            <select class="form-control " type="text" id="combooffer" name="combooffer">
                                <option value="">All</option>
                                @foreach ($comboOffers as $comboOffer)
                                    <option value="{{ $comboOffer->id }}">
                                        {{ $comboOffer->treatments->pluck('treat_name')->implode(', ') }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-md-3 col-lg-2">
                        <div class="form-group">
                            <label class="form-label" for="registration">Registration</label>
                            <select class="form-control " type="text" id="registration" name="registration">
                                <option value="">All</option>
                                @foreach ($billStaffs as $billStaff)
                                    <option value="{{ $billStaff->id }}">
                                        {{ str_replace('<br>', ' ', $billStaff->name) }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>

            </div>
            <div class="box-footer p-3 px-0 text-end " style="border-radius: 0px;">
                <button type="submit" class="btn btn-success" id="searchcollectionbtn">
                    <i class="fa fa-search"></i> Search
                </button>
            </div>
        </div>
    </div>
    <div class="collectiondiv container" style="display: none;">
        <div class="table-responsive" style=" width: 100%;
    overflow-x: auto;">
            <table class="table table-bordered table-hover table-striped mb-0 data-table text-center"
                id="collectionTable" width="100%">
                <thead class="bg-primary-light">
                    <tr>
                        <th>#</th>
                        <th>Date</th>
                        <th>Patient ID</th>
                        <th>Patient Name</th>
                        <th>Branch</th>
                        <th>Visit</th>
                        <th>Bill Type</th>
                        <th>Total</th>
                        <th>Discount</th>
                        <th>Tax</th>
                        <th>Net</th>
                        <th>Cash</th>
                        <th>Gpay</th>
                        <th>Card</th>
                        <th>Total Paid</th>
                        <th>Balance Given</th>
                        <th>Outstanding</th>
                        <th>Created By</th>
                        <th>Updated By</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
                <tfoot>
                    <tr class="bt-3 border-primary">
                        {{-- <th colspan="7">Total:</th> --}}
                        <th colspan="6"></th>
                        <th>Total:</th>
                        <th id="total-sum"></th>
                        <th id="total-dis"></th>
                        <th id="total-tax"></th>
                        <th id="total-net"></th>
                        <th id="total-cash"></th>
                        <th id="total-gpay"></th>
                        <th id="total-card"></th>
                        <th id="total-paid"></th>
                        <th id="total-balance"></th>
                        <th id="total-due"></th>
                        <th colspan="2"></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</form>
<script type="text/javascript">
    var table;
    jQuery(function($) {
        var clinicBasicDetails = @json($clinicBasicDetails);

        $('#searchcollectionbtn').click(function(e) {
            e.preventDefault(); // Prevent form submission

            if ($.fn.DataTable.isDataTable("#collectionTable")) {
                // Destroy existing DataTable instance
                // table.destroy();
                $('#collectionTable').DataTable().destroy();
            }

            // Initialize DataTable
            table = $('#collectionTable').DataTable({
                processing: true,
                serverSide: true,
                // responsive: true,
                ajax: {
                    url: "{{ route('report.collection') }}",
                    type: 'POST',
                    data: function(d) {
                        d._token = $('input[name="_token"]').val();
                        d.fromdate = $('#fromdate').val();
                        d.todate = $('#todate').val();
                        d.branch = $('#branch').val();
                        d.billedby = $('#billedby').val();
                        d.generatedby = $('#generatedby').val();
                        d.outstanding = $('#outstanding').val();
                        d.combooffer = $('#combooffer').val();
                        d.registration = $('#registration').val();
                    },
                    dataSrc: function(json) {
                        return json.data; // Ensure `json.data` is correct
                    }
                },
                columns: [{
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex',
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'billDate',
                        name: 'billDate',
                        className: 'min-w-60',
                        render: function(data, type, row) {
                            if (data) {
                                // Convert the date string to a JavaScript Date object
                                var date = new Date(data);

                                // Format the date as d-m-y
                                var day = ("0" + date.getDate()).slice(-2);
                                var month = ("0" + (date.getMonth() + 1)).slice(-2);
                                var year = date.getFullYear();

                                return day + '-' + month + '-' +
                                    year; // Return formatted date
                            } else {
                                return '-'; // Return dash if no data is present
                            }
                        }
                    },
                    {
                        data: 'patientId',
                        name: 'patientId'
                    },
                    {
                        data: 'patientName',
                        name: 'patientName'
                    },
                    {
                        data: 'branch',
                        name: 'branch'
                    },
                    {
                        data: 'visitCount',
                        name: 'visitCount'
                    },
                    {
                        data: 'billType',
                        name: 'billType'
                    },
                    {
                        data: 'total',
                        name: 'total'
                    },
                    {
                        data: 'discount',
                        name: 'discount'
                    },
                    {
                        data: 'tax',
                        name: 'tax'
                    },
                    {
                        data: 'netAmount',
                        name: 'netAmount'
                    },
                    {
                        data: 'cash',
                        name: 'cash'
                    },
                    {
                        data: 'gpay',
                        name: 'gpay'
                    },
                    {
                        data: 'card',
                        name: 'card'
                    },
                    {
                        data: 'totalPaid',
                        name: 'totalPaid'
                    },
                    {
                        data: 'balanceGiven',
                        name: 'balanceGiven'
                    },
                    {
                        data: 'outstanding',
                        name: 'outstanding'
                    },
                    {
                        data: 'createdBy',
                        name: 'createdBy'
                    },
                    {
                        data: 'updatedBy',
                        name: 'updatedBy'
                    }
                ],

                dom: 'Bfrtlp',
                lengthMenu: [
                    [10, 25, 50, -1],
                    [10, 25, 50, 'All']
                ],
                // select: true,
                buttons: [{
                        extend: 'print',
                        text: 'Print',
                        // className: 'btn btn-primary',
                        title: clinicBasicDetails.clinic_name,
                        messageTop: 'Collection Report',
                        orientation: 'landscape',
                        pageSize: 'A4',
                        footer: true,
                        filename: 'Collection Report',
                        exportOptions: {
                            columns: ':visible'
                        },
                        customize: function(win) {
                            $(win.document.body).css('font-size', '10pt');
                            $(win.document.body).find('table').addClass('compact').css(
                                'font-size',
                                'inherit');
                        }
                    },

                    {
                        extend: 'excelHtml5',
                        text: 'Excel',
                        // className: 'btn btn-success',
                        title: clinicBasicDetails.clinic_name,
                        messageTop: 'Collection Report',
                        footer: true,
                        filename: 'Collection Report',
                        exportOptions: {
                            columns: ':visible'
                        }
                    },
                    {
                        extend: 'pdfHtml5',
                        text: 'PDF',
                        // className: 'btn btn-danger',
                        title: clinicBasicDetails.clinic_name,
                        messageTop: 'Collection Report',
                        orientation: 'landscape',
                        pageSize: 'A3',
                        exportOptions: {
                            columns: ':visible'
                        },
                        footer: true,
                        headerRows: 1,
                        filename: 'Collection Report',
                        customize: function(doc) {
                            // doc.content[1].table.widths = ['*', '*', '*', '*', '*', '*', '*', '*',
                            //     '*', '*'
                            // ];
                            doc.defaultStyle.fontSize = 10;
                            doc.styles.tableHeader.fontSize = 10;

                        }
                    }
                ],
                footerCallback: function(row, data, start, end, display) {
                    var api = this.api();

                    for (let i = 7; i < 17; i++) {
                        var total = api.column(i).data().reduce(function(a, b) {
                            return parseFloat(a) + parseFloat(b);
                        }, 0);
                        $(api.column(i).footer()).html(total.toFixed(2));
                    }
                }
            });

            $('.collectiondiv').show();
        });

    });
</script>
