<?php use Illuminate\Support\Facades\Session; ?>
@extends('layouts.dashboard')
@section('title', 'Billing')
@section('content')

    <div class="content-wrapper">
        <div class="container-full">
            <div class="content-header">
                <div class="d-flex align-items-center justify-content-between">
                    <h3 class="page-title">Billing :<span class="fs-20 text-info">
                            <?= Session::get('patientId') ?>- <?= Session::get('patientName') ?>
                        </span>
                    </h3>
                    <div>
                        <button type='button'
                            class='waves-effect waves-light btn btn-circle btn-info btn-pdf-generate btn-xs me-1'
                            title='Download' data-bs-toggle='modal' data-app-id='{$row->id}' data-parent-id='{$parent_id}'
                            data-patient-id='{$row->patient->patient_id}' data-bs-target='#modal-download'><i
                                class='fa fa-download'></i></button>
                        <button type='button'
                            class='waves-effect waves-light btn btn-circle btn-warning buttons-print btn-pdf-generate btn-xs me-1'
                            title='Print' data-bs-toggle='modal' data-app-id='{$row->id}' data-parent-id='{$parent_id}'
                            data-patient-id='{$row->patient->patient_id}' data-bs-target='#modal-download'><i
                                class='fa fa-print'></i></button>
                        <a type="button" class="waves-effect waves-light btn btn-primary btn-circle btn-xs me-1"
                            href="{{ route('billing') }}">
                            <i class="fa-solid fa-angles-left"></i></a>
                    </div>
                </div>
                <div id="error-message-container">
                    <p id="error-message"
                        class="myadmin-alert myadmin-alert-icon myadmin-alert-click alert-danger alerttop fadeOut"
                        style="display: none;"></p>
                </div>
            </div>

            <section class="content">
                <div class=" row invoice-info">
                    <div class=" col-sm-12 invoice-col mb-15">
                        <div class="flexbox invoice-details px-1   no-margin">
                            <div>
                                <p class="mb-1"><b>Bill No:</b> 7541296</p>
                                <p class="mb-0"><b>Generated at:</b> 14/08/2024 10:30 AM</p>
                            </div>
                            <div><b>Appointment ID:</b> 7541296</div>
                            <div><b>Mobile No.:</b> 7541291610</div>
                            <div class="text-end">
                                <p class="mb-1"><b>Payment Due:</b> 14/08/2018</p>
                                <p class="mb-0"><b>Generated by:</b> Name</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 table-responsive-sm lh-1">
                        <table class="table table-bordered caption-top text-center">
                            <caption class="pt-0">Treatment Details</caption>
                            <tbody>
                                <tr>
                                    <th style="width: 5%;">#</th>
                                    <th style="width: 45%;">Treatment</th>
                                    <th style="width: 10%;">Quantity</th>
                                    <th style="width: 15%;">Unit Cost</th>
                                    <th style="width: 10%;">Discount</th>
                                    <th style="width: 15%;">Subtotal</th>
                                </tr>
                                <tr>
                                    <td>1</td>
                                    <td class="text-start">Root Canal</td>
                                    <td>2</td>
                                    <td>&#8377; 26.00</td>
                                    <td>12</td>
                                    <td>&#8377; 52.00</td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td class="text-start">Tooth Cleaning</td>
                                    <td>1</td>
                                    <td>&#8377; 1500.00</td>
                                    <td>2</td>
                                    <td>&#8377; 1500.00</td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td class="text-start">Dental Surgery</td>
                                    <td>2</td>
                                    <td>&#8377; 540.00</td>
                                    <td>-</td>
                                    <td>&#8377; 1080.00</td>
                                </tr>
                                <tr>
                                    <td>4</td>
                                    <td class="text-start">Root canal</td>
                                    <td>3</td>
                                    <td>&#8377; 320.00</td>
                                    <td>-</td>
                                    <td>&#8377; 960.00</td>
                                </tr>
                            </tbody>
                            <tbody>
                                <tr>
                                    <td colspan="2" class="text-start">
                                        <input type="checkbox" id="combo_checkbox" name="combo_checkbox"
                                            class="filled-in chk-col-success " />
                                        <label for="combo_checkbox">Combo offers</label>
                                    </td>
                                    <td colspan="3" class="text-end">Sub - Total amount</td>
                                    <td>&#8377; 3,592.00</td>
                                </tr>
                                <tr>
                                    <td colspan="2" class="text-start">
                                        <input type="checkbox" id="medicine_checkbox" name="medicine_checkbox"
                                            class="filled-in chk-col-success " />
                                        <label for="medicine_checkbox">Medicines</label>
                                    </td>
                                    <td colspan="3" class="text-end">Combo Offer</td>
                                    <td>&#8377; 3,592.00</td>
                                </tr>
                                <tr>
                                    <td colspan="2" class="text-start">
                                        <input type="checkbox" id="insurance_checkbox" name="insurance_checkbox"
                                            class="filled-in chk-col-success" />
                                        <label for="insurance_checkbox">Insurance</label>
                                    </td>
                                    <td colspan="3" class="text-end">Insurance</td>
                                    <td>&#8377; 3,592.00</td>
                                </tr>
                                <tr>
                                    <td colspan="2"></td>
                                    <td colspan="3" class="text-end">Doctor Discount (20%)</td>
                                    <td>&#8377; 110.44</td>
                                </tr>
                                <tr>
                                    <td colspan="2"></td>
                                    <td colspan="3" class="text-end">Tax (18%)</td>
                                    <td>&#8377; 646.56</td>
                                </tr>
                                <tr class="bt-3 border-primary">
                                    <td colspan="5" class="text-end ">
                                        <h3><b>Total</b></h3>
                                    </td>
                                    <td>
                                        <h3>&#8377; 4,349.00</h3>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="5" class="text-end ">Paid Amount</td>
                                    <td>&#8377; 4,350.00</td>
                                </tr>
                                <tr>
                                    <td colspan="5" class="text-end ">Balance</td>
                                    <td>&#8377; 1.00</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="row text-end py-3">
                    <div class="col-12">
                        <button type="button" class="btn btn-success pull-right"><i class="fa fa-credit-card"></i>
                            Submit Payment
                        </button>
                    </div>
                </div>

            </section>
        </div>
    </div>

    @include('billing.combo_offer')
    @include('billing.insurance')
    @include('billing.medicine')

    <script src="{{ asset('js/billing.js') }}"></script>
@endsection
