<?php

use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Session; ?>
@extends('layouts.dashboard')
@section('title', 'Billing')
@section('content')

    <div class="content-wrapper">
        <div class="container-full">
            <div class="content-header">
                <div class="d-flex align-items-center justify-content-between">
                    <h3 class="page-title">Billing :<span class="fs-20 text-info">
                            {{ $appointment->patient_id}}- {{str_replace('<br>', ' ', $appointment->patient->first_name . ' ' . $appointment->patient->last_name)}}
                        </span>
                    </h3>
                    <?php  $base64Id = base64_encode($appointment->id);
                            $idEncrypted = Crypt::encrypt($base64Id); ?>
                                
                                <div>
    <?php if (sizeof($prescriptions) > 0 && $isMedicineProvided == 'Y') { ?> 
        <a href="{{ route('medicineBilling.create', ['appointmentId' => $idEncrypted]) }}" class="btn btn-success float-end">Medicine Bill</a> 
    <?php } ?>
    <a href="{{ route('billing.create', ['appointmentId' => $idEncrypted]) }}" class="btn btn-success float-end">Treatment Bill</a>
</div>
<div>
                        <button type='button'
                            class='waves-effect waves-light btn btn-circle btn-info btn-pdf-generate btn-xs me-1'
                            title='Download' data-bs-toggle='modal' data-app-id='{$row->id}' data-parent-id='{$parent_id}'
                            data-patient-id='{$row->patient->patient_id}' data-bs-target='#modal-download'><i
                                class='fa fa-download'></i></button>
                        <button type='button'
                            class='waves-effect waves-light btn btn-circle btn-warning buttons-print btn-pdf-generate btn-xs me-1'
                            title='Print' data-bs-toggle='modal' data-app-id='{$row->id}' data-parent-id='{$parent_id}'
                            data-patient-id='{$row->patient->patient_id}' data-bs-target='#modal-download'><i
                                class='fa fa-print'></i></button>
                        <a type="button" class="waves-effect waves-light btn btn-primary btn-circle btn-xs me-1"
                            href="{{ route('billing') }}">
                            <i class="fa-solid fa-angles-left"></i></a>
                    </div>
                </div>
                <div id="error-message-container">
                    <p id="error-message"
                        class="myadmin-alert myadmin-alert-icon myadmin-alert-click alert-danger alerttop fadeOut"
                        style="display: none;"></p>
                </div>
            </div>

            <section class="content">
                <div class=" row invoice-info">
                    <div class=" col-sm-12 invoice-col mb-15">
                        <div class="flexbox invoice-details px-1   no-margin">
                            <div>
                                <p class="mb-1"><b>Bill No:</b> 7541296</p>
                                <input type="hidden" id="appointmentId" value="{{ $idEncrypted }}">
                                <p class="mb-0"><b>Generated at:</b>{{ date ('d/m/Y H:m:s')}}</p>
                            </div>
                            <div><b>Appointment ID:</b> {{ $appointment->app_id}}</div>
                            <div><b>Mobile No.:</b> {{ $appointment->patient->phone}}</div>
                            <div class="text-end">
                                <p class="mb-1"><b>Payment Due:</b> {{ date('d/m/Y') }}</p>
                                <p class="mb-0"><b>Generated by:</b> {{ Auth::user()->name}}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 table-responsive-sm lh-1">
                        <table class="table table-bordered caption-top text-center">
                            <caption class="pt-0">Treatment Details</caption>
                            <tbody>
                                <tr>
                                    <th style="width: 5%;">#</th>
                                    <th style="width: 45%;">Treatment</th>
                                    <th style="width: 10%;">Quantity</th>
                                    <th style="width: 15%;">Unit Cost ( {{session::get('currency')}} )</th>
                                    <th style="width: 10%;">Discount ( % )</th>
                                    <th style="width: 15%;">Subtotal ( {{session::get('currency')}} )</th>
                                </tr>
                                <?php $i = 0;
                                $treatmentTotal = 0; ?>
                                @foreach ( $individualTreatmentAmounts as $individualTreatmentAmount )
                                <?php
                                $i++;
                                $cost = is_numeric($individualTreatmentAmount['cost']) ? floatval($individualTreatmentAmount['cost']) : 0;
                                $subtotal = is_numeric($individualTreatmentAmount['subtotal']) ? floatval($individualTreatmentAmount['subtotal']) : 0;
                        
                                ?>
                                    <tr>
                                        <td>{{ $i }}</td>
                                        <td class="text-start">{{ $individualTreatmentAmount['treat_name'] }}
                                            <input type="hidden" name="treatmentId{{$i}}" value="{{ $individualTreatmentAmount['treat_id'] }}">
                                        </td>
                                        <td><input type="text" readonly name="quantity{{$i}}" class="form-control text-center" value="{{ $individualTreatmentAmount['quantity'] }}"></td> <!-- Add quantity if available -->
                                        <td><input type="text" readonly name="cost{{$i}}" class="form-control text-center" value="{{ number_format($individualTreatmentAmount['cost'], 3)}}"></td>
                                       <td> <input type="text" readonly name="discount_percentage{{$i}}" class="form-control text-center" value="{{ $individualTreatmentAmount['discount_percentage'] }}"></td>    
                                        
                                        <td> <input type="text" readonly name="subtotal{{$i}}" class="form-control text-center" value="{{ number_format($individualTreatmentAmount['subtotal'], 3) }}"></td> <!-- Format the cost -->
                                        <?php

                                        // $treatmentTotal += number_format($individualTreatmentAmount['subtotal'], 3)
                                        $treatmentTotal += $subtotal;
                                        ?>
                                    </tr>   
                                @endforeach
                                @if ($checkAppointmentCount == 1) 
                                    <tr>
                                    <td>{{ ++$i }}</td>
                                        <td class="text-start">Registration Fees
                                            <input type="hidden" name="regFees">
                                        </td>
                                        <td><input type="text" readonly name="reg_quantity" class="form-control text-center" value="1"></td> <!-- Add quantity if available -->
                                        <td><input type="text" readonly name="regCost" class="form-control text-center" value="{{ number_format($clinicBasicDetails->patient_registration_fees, 3) }}"></td>
                                       <td> <input type="text" readonly name="regDiscount" class="form-control text-center" value="0"></td>    
                                        
                                        <td> <input type="text" readonly name="regAmount" class="form-control text-center" value="{{ number_format($clinicBasicDetails->patient_registration_fees, 3) }}"></td> <!-- Format the cost -->
                                        <?php

                                        $treatmentTotal += number_format($clinicBasicDetails->patient_registration_fees, 3)
                                        ?>
                                    </tr>  
                                    @endif
                                    @if ($consultationFees == 1) 
                                    <tr>
                                    <td>{{ ++$i }}</td>
                                        <td class="text-start">Consultation Fees
                                            <input type="hidden" name="consultationFees">
                                        </td>
                                        <td><input type="text" readonly name="consultationFees_quantity" class="form-control text-center" value="1"></td> <!-- Add quantity if available -->
                                        <td><input type="text" readonly name="consultationFeesCost" class="form-control text-center" value="{{ number_format($fees, 3) }}"></td>
                                       <td> <input type="text" readonly name="consultationFeesDiscount" class="form-control text-center" value="0"></td>    
                                        
                                        <td> <input type="text" readonly name="consultationFeesAmount" class="form-control text-center" value="{{ number_format($fees, 3) }}"></td> <!-- Format the cost -->
                                        <?php

                                        $treatmentTotal += number_format($fees, 3)
                                        ?>
                                    </tr>  
                                    @endif

                                
                            </tbody>
                            <tbody>
                                <tr>
                                    <td colspan="5" class="text-end">Sub - Total amount</td>
                                    <td><input type="text" readonly name="treatmenttotal" id="treatmenttotal" class="form-control text-center" value="{{ number_format($treatmentTotal, 3) }}"> </td>
                                </tr>
                                <?php if (sizeof($combOffers) > 0) { ?>
                                    <tr>
                                        <td colspan="5" class="text-end">
                                        <a href="#" data-bs-toggle="modal" data-bs-target="#modal-combo">
                                            <span class="text-danger">(Select Offer)</span></a>

                                        <label for="combo_checkbox">Combo offer Discount</label></td>
                                        <?php $treatmentTotal -= $comboOfferDeduction; ?>
                                        <td><input type="text" readonly name="comboOfferAmount" id ="comboOfferAmount" class="form-control text-center" value="{{ number_format($comboOfferDeduction, 3) }}"> </td>
                                    </tr> 
                                <?php  } ?>
                                <!-- <tr>
                                    <td colspan="5" class="text-end">Combo Offer</td>
                                    <td>{{ session('currency') }}</td>
                                </tr> -->
                                @if ($insuranceApproved) 
                                <tr>
                                <tr>
                                        <td colspan="5" class="text-end">Insurance paid</td>
                                        <?php $treatmentTotal -= $insurance; ?>
                                        <td><input type="text" readonly name="insurance" id ="insurance" class="form-control text-center" value="{{ number_format($insurance, 3) }}"> </td>
                                    </tr> 
                                </tr>
                                @endif
                                @if ($doctorDiscount != 0)
                                <tr>
                                    <td colspan="5" class="text-end">Doctor Discount ({{$doctorDiscount}}) %</td>
                                    <?php 
                                    $doctorDisc = $treatmentTotal * ($doctorDiscount/100);
                                    $treatmentTotal = $treatmentTotal - $doctorDisc;
                                    ?>
                                    <td><input type="text" readonly name="doctorDisc" id="doctorDisc" class="form-control text-center" value="{{ number_format($doctorDisc, 3) }}"> </td>
                                </tr>
                                @endif
                                @if ($clinicBasicDetails->treatment_tax_included == 'N') 
                                <tr>
                                    <td colspan="5" class="text-end">Tax ({{$clinicBasicDetails->tax}}%)</td>
                                    <?php 
                                    $taxAmount = $treatmentTotal * ($clinicBasicDetails->tax / 100);
                                    $treatmentTotal += $taxAmount;?>
                                    <td><input type="text" readonly name="treatmenttotal" class="form-control text-center" value="{{ number_format($taxAmount, 3) }}"></td>
                                </tr>
                                @endif
                                <tr class="bt-3 border-primary">
                                    <td colspan="5" class="text-end ">
                                        <h3><b>Total</b></h3>
                                    </td>
                                    <td>
                                        <h3>{{ session('currency') }}{{ number_format($treatmentTotal, 2) }}
                                        <input type="hidden" name="totaltoPay" id="totalToPay" class="form-control text-center" value="{{ $treatmentTotal }}">
                                        </h3>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="5" class="text-end ">Paid Amount</td>
                                    <td><input type="text" name="amountPaid" id="amountPaid" class="form-control text-center" ></td>
                                </tr>
                                <tr>
                                    <td colspan="5" class="text-end ">Balance</td>
                                    <td><input type="text" name="balance" id="balance" class="form-control text-center" ></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="row text-end py-3">
                    <div class="col-12">
                        <button type="button" class="btn btn-success pull-right"><i class="fa fa-credit-card"></i>
                            Submit Payment
                        </button>
                    </div>
                </div>

            </section>
        </div>
    </div>

    @include('billing.combo_offer')
    @include('billing.insurance')
    

    <script src="{{ asset('js/billing.js') }}"></script>
@endsection
