<?php

use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Session; ?>
@extends('layouts.dashboard')
@section('title', 'Billing')
@section('content')

    <div class="content-wrapper">
        <div class="container-full">
            <div class="content-header">
                <div class="d-flex align-items-center justify-content-between">
                    <h3 class="page-title">Billing :<span class="fs-20 text-info">
                            {{ $appointment->patient_id}}- {{str_replace('<br>', ' ', $appointment->patient->first_name . ' ' . $appointment->patient->last_name)}}
                        </span>
                    </h3>
                    <?php  $base64Id = base64_encode($appointment->id);
                            $idEncrypted = Crypt::encrypt($base64Id); ?>
                                
                                <div>
    <?php //if (sizeof($prescriptions) > 0 && $isMedicineProvided == 'Y') { ?> 
        <a href="{{ route('medicineBilling.create', ['appointmentId' => $idEncrypted]) }}" class="btn btn-success float-end">Medicine Bill</a> 
    <?php //} ?>
    <a href="{{ route('billing.create', ['appointmentId' => $idEncrypted]) }}" class="btn btn-success float-end">Treatment Bill</a>
</div>
<div>
                        <button type='button'
                            class='waves-effect waves-light btn btn-circle btn-info btn-pdf-generate btn-xs me-1'
                            title='Download' data-bs-toggle='modal' data-app-id='{$row->id}' data-parent-id='{$parent_id}'
                            data-patient-id='{$row->patient->patient_id}' data-bs-target='#modal-download'><i
                                class='fa fa-download'></i></button>
                        <button type='button'
                            class='waves-effect waves-light btn btn-circle btn-warning buttons-print btn-pdf-generate btn-xs me-1'
                            title='Print' data-bs-toggle='modal' data-app-id='{$row->id}' data-parent-id='{$parent_id}'
                            data-patient-id='{$row->patient->patient_id}' data-bs-target='#modal-download'><i
                                class='fa fa-print'></i></button>
                        <a type="button" class="waves-effect waves-light btn btn-primary btn-circle btn-xs me-1"
                            href="{{ route('billing') }}">
                            <i class="fa-solid fa-angles-left"></i></a>
                    </div>
                </div>
                <div id="error-message-container">
                    <p id="error-message"
                        class="myadmin-alert myadmin-alert-icon myadmin-alert-click alert-danger alerttop fadeOut"
                        style="display: none;"></p>
                </div>
            </div>

            <section class="content">
                <div class=" row invoice-info">
                    <div class=" col-sm-12 invoice-col mb-15">
                        <div class="flexbox invoice-details px-1   no-margin">
                            <div>
                                <p class="mb-1"><b>Bill No:</b> {{$billExists->bill_id}}</p>
                                <input type="hidden" id="appointmentId" value="{{ $idEncrypted }}">
                                <p class="mb-0"><b>Created at:</b>{{$billExists->updated_at}}</p>
                            </div>
                            <div><b>Appointment ID:</b> {{ $appointment->app_id}}</div>
                            <div><b>Mobile No.:</b> {{ $appointment->patient->phone}}</div>
                            <div class="text-end">
                                <p class="mb-1"><b>Payment Due:</b> {{ date('d/m/Y') }}</p>
                                <p class="mb-0"><b>Generated by:</b> {{ Auth::user()->name}}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 table-responsive-sm lh-1">
                        <table class="table table-bordered caption-top text-center">
                            <caption class="pt-0">Treatment Details</caption>
                            <tbody>
                                <tr>
                                    <th style="width: 5%;">#</th>
                                    <th style="width: 45%;">Treatment</th>
                                    <th style="width: 10%;">Quantity</th>
                                    <th style="width: 15%;">Unit Cost ( {{session::get('currency')}} )</th>

                                    <th style="width: 10%;">Discount ( % )</th>
                                    
                                    <th style="width: 15%;">Subtotal ( {{session::get('currency')}} )</th>
                                </tr>
                                <?php $i = 0;
                                $treatmentTotal = 0; ?>
                                @foreach ( $detailBills as $detailBill )
                                <?php
                                $i++;
                                $cost = is_numeric($detailBill->cost) ? floatval($detailBill->cost) : 0;
                                // $subtotal = is_numeric($detailBill->amount) ? floatval($detailBill->amount) : 0;
                        
                                ?>
                                    <tr>
                                        <td>{{ $i }}</td>
                                        <td class="text-start">{{ $detailBill->treatment_id ? $detailBill->treatment_id  :  $detailBill->consultation_registration}}
                                            <input type="hidden" name="treatmentId{{$i}}" value="{{ $detailBill->treatment_id }}">
                                        </td>
                                        <td><input type="text" readonly name="quantity{{$i}}" class="form-control text-center" value="{{ $detailBill->quantity }}"></td> <!-- Add quantity if available -->
                                        <td><input type="text" readonly name="cost{{$i}}" class="form-control text-center" value="{{ number_format($detailBill->cost, 3)}}"></td>
                                       <td> <input type="text" readonly name="discount_percentage{{$i}}" class="form-control text-center" value="{{ $detailBill->discount }}"></td>    
                                        
                                        <td> <input type="text" readonly name="subtotal{{$i}}" class="form-control text-center" value="{{ $detailBill->amount}}"></td> <!-- Format the cost -->
                                        <?php

                                        // $treatmentTotal += number_format($individualTreatmentAmount['subtotal'], 3)
                                       
                                        ?>
                                    </tr>   
                                @endforeach
                                    
                                
                            </tbody>
                            <tbody>
                                <tr>
                                    <td colspan="5" class="text-end">Sub - Total amount</td>
                                    <td><input type="text" readonly name="treatmenttotal" id="treatmenttotal" class="form-control text-center" value="{{ number_format($billExists->treatment_total_amount, 3) }}"> </td>
                                </tr>
                                <?php if ($billExists->combo_offer_deduction != 0) { ?>
                                    <tr>
                                        <td colspan="5" class="text-end">
                                     

                                        <label for="combo_checkbox">Combo offer Discount</label></td>
                                        
                                        <td><input type="text" readonly name="comboOfferAmount" id ="comboOfferAmount" class="form-control text-center" value="{{ number_format($billExists->combo_offer_deduction, 3) }}"> </td>
                                    </tr> 
                                <?php  } ?>
                                <!-- <tr>
                                    <td colspan="5" class="text-end">Combo Offer</td>
                                    <td>{{ session('currency') }}</td>
                                </tr> -->
                                @if ($billExists->insurance_paid) 
                                <tr>
                                <tr>
                                        <td colspan="5" class="text-end">Insurance paid</td>
                                        <td><input type="text" readonly name="insurance" id ="insurance" class="form-control text-center" value="{{ number_format($billExists->insurance_paid, 3) }}"> </td>
                                    </tr> 
                                </tr>
                                @endif
                                @if ($billExists->doctor_discount != 0)
                                <tr>
                                    <td colspan="5" class="text-end">Doctor Discount () %</td>
                                    
                                    <td><input type="text" readonly name="doctorDisc" id="doctorDisc" class="form-control text-center" value="{{ number_format($billExists->doctor_discount, 3) }}"> </td>
                                </tr>
                                @endif
                                <tr>
                                    <td colspan="5" class="text-end">Tax ()</td>
                                  
                                    <td><input type="text" readonly name="treatmenttotal" class="form-control text-center" value="{{ number_format(0, 3) }}"></td>
                                </tr>
                                
                                <tr class="bt-3 border-primary">
                                    <td colspan="5" class="text-end ">
                                        <h3><b>Total</b></h3>
                                    </td>
                                    <td>
                                        <h3>{{ session('currency') }}{{ number_format($billExists->amount_to_be_paid, 2) }}
                                        <input type="hidden" name="totaltoPay" id="totalToPay" class="form-control text-center" value="{{ $billExists->amount_to_be_paid }}">
                                        </h3>
                                    </td>
                                </tr>
                                <tr>
                                <td colspan="3">
    <span class="text-bold">Mode of Payment : </span>
    <input type="radio" class="form-check-input" name="mode_of_payment" id="mode_of_payment_gpay" value="gpay">
        <label class="form-check-label" for="mode_of_payment_gpay">Gpay</label>
    <input type="radio" class="form-check-input" name="mode_of_payment" id="mode_of_payment_cash" value="cash">
        <label class="form-check-label" for="mode_of_payment_cash">Cash</label>
    <input type="radio" class="form-check-input" name="mode_of_payment" id="mode_of_payment_insurance" value="insurance">
        <label class="form-check-label" for="mode_of_payment_insurance">Insurance</label>
    </td>

                                    <td colspan="2" class="text-end ">Paid Amount</td>
                                    <td><input type="text" name="amountPaid" id="amountPaid" class="form-control text-center" ></td>
                                </tr>
                                <tr>
                                    <td colspan="5" class="text-end ">Balance</td>
                                    <td><input type="text" name="balance" id="balance" class="form-control text-center" ></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="row text-end py-3">
                    <div class="col-12">
                        <button type="button" class="btn btn-success pull-right"><i class="fa fa-credit-card"></i>
                            Submit Payment
                        </button>
                    </div>
                </div>

            </section>
        </div>
    </div>


    <script src="{{ asset('js/billing.js') }}"></script>
@endsection
