<?php

use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Session; ?>
@extends('layouts.dashboard')
@section('title', 'Billing')
@section('content')

    <div class="content-wrapper">
        <div class="container-full">
            <div class="content-header">
                <div class="d-flex align-items-center justify-content-between">
                    <h3 class="page-title">Billing :<span class="fs-20 text-info">
                            {{ $appointment->patient_id}}- {{str_replace('<br>', ' ', $appointment->patient->first_name . ' ' . $appointment->patient->last_name)}}
                        </span>
                    </h3>
                    <?php  $base64Id = base64_encode($appointment->id);
                            $idEncrypted = Crypt::encrypt($base64Id); ?>
                                
                                <div>
    <?php if (sizeof($prescriptions) > 0 && $isMedicineProvided == 'Y') { ?> 
        <a href="{{ route('medicineBilling.create', ['appointmentId' => $idEncrypted]) }}" class="btn btn-success float-end">Medicine Bill</a> 
    <?php } ?>
    <a href="{{ route('billing.create', ['appointmentId' => $idEncrypted]) }}" class="btn btn-success float-end">Treatment Bill</a>
</div>
<div>
                        <button type='button'
                            class='waves-effect waves-light btn btn-circle btn-info btn-pdf-generate btn-xs me-1'
                            title='Download' data-bs-toggle='modal' data-app-id='{$row->id}' data-parent-id='{$parent_id}'
                            data-patient-id='{$row->patient->patient_id}' data-bs-target='#modal-download'><i
                                class='fa fa-download'></i></button>
                        <button type='button'
                            class='waves-effect waves-light btn btn-circle btn-warning buttons-print btn-pdf-generate btn-xs me-1'
                            title='Print' data-bs-toggle='modal' data-app-id='{$row->id}' data-parent-id='{$parent_id}'
                            data-patient-id='{$row->patient->patient_id}' data-bs-target='#modal-download'><i
                                class='fa fa-print'></i></button>
                        <a type="button" class="waves-effect waves-light btn btn-primary btn-circle btn-xs me-1"
                            href="{{ route('billing') }}">
                            <i class="fa-solid fa-angles-left"></i></a>
                    </div>
                </div>
                <div id="error-message-container">
                    <p id="error-message"
                        class="myadmin-alert myadmin-alert-icon myadmin-alert-click alert-danger alerttop fadeOut"
                        style="display: none;"></p>
                </div>
            </div>

            <section class="content">
                <div class=" row invoice-info">
                    <div class=" col-sm-12 invoice-col mb-15">
                        <div class="flexbox invoice-details px-1   no-margin">
                            <div>
                                <p class="mb-1"><b>Bill No:</b> 7541296</p>
                                <input type="hidden" id="appointmentId" value="{{ $idEncrypted }}">
                                <p class="mb-0"><b>Generated at:</b>{{ date ('d/m/Y H:m:s')}}</p>
                            </div>
                            <div><b>Appointment ID:</b> {{ $appointment->app_id}}</div>
                            <div><b>Mobile No.:</b> {{ $appointment->patient->phone}}</div>
                            <div class="text-end">
                                <p class="mb-1"><b>Payment Due:</b> {{ date('d/m/Y') }}</p>
                                <p class="mb-0"><b>Generated by:</b> {{ Auth::user()->name}}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 table-responsive-sm lh-1">
                        <table class="table table-bordered caption-top text-center">
                            <caption class="pt-0">Prescription Details</caption>
                            <thead class="bg-dark">
                                <tr>
                                    <th style="width:30%;" class="text-start">Medicine</th>
                                    <th style="width:10%;">Duration</th>
                                    <th style="width:15%;">Dosage</th>
                                    <th style="width:10%;">Quantity</th>
                                    <th style="width:15%;" class="text-center">Status</th>
                                    <th style="width:20%;" class="text-center">Rate ({{$clinicBasicDetails->currency}})</th>
                                </tr>
                            </thead>
                            <tbody id="tablebody">
                                <?php foreach ($prescriptions as $prescription) { ?>
                                <tr>
                                    <td class="text-start"><input type="checkbox" id="medicine_checkbox1"
                                            name="medicine_checkbox1" class="filled-in chk-col-success" value="{{$prescription->id}}"/>
                                        <label for="medicine_checkbox1">
                                            {{  $prescription->medicine->med_name }}</label>
                                    </td>
                                    <td>
                                        <div class="input-group col-12">
                                            <input type="number" class="form-control text-center" id="duration"
                                                name="duration" aria-describedby="basic-addon2" value="{{ $prescription->duration}}"
                                                required>
                                            <div class="input-group-append">
                                                <span class="input-group-text" id="basic-addon2">days</span>
                                            </div>
                                        </div>
                                    </td>
                                    <th>{{  $prescription->dosage->dos_name}}</th>
                                    <th><input type="number" name="quantity" id="quantity" class="form-control text-center"></th>
                                   
                                    <td>{{$prescription->medicine->stock_status}}</td>
                                    <td><input type="text" class="form-control text-center" id="rate"
                                                name="rate" aria-describedby="basic-addon2" 
                                                required></td>
                                </tr><?php } ?>
                                
                            </tbody>
                            <tbody>
                                <tr>
                                    <th colspan="5" class="text-end">Total</th>
                                    <th><input type="text" class="form-control text-center" id="total"
                                                name="total" aria-describedby="basic-addon2" 
                                                required></th>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="row text-end py-3">
                    <div class="col-12">
                        <button type="button" class="btn btn-success pull-right"><i class="fa fa-credit-card"></i>
                            Submit Payment
                        </button>
                    </div>
                </div>

            </section>
        </div>
    </div>

    <script src="{{ asset('js/billing.js') }}"></script>
@endsection
