<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Session;

date_default_timezone_set('Asia/Kolkata');

$idEncryptedBill = '';
$base64Id = base64_encode($appointment->id);
$idEncrypted = Crypt::encrypt($base64Id);
if ($hasPrescriptionBill) {
    $base64BillId = base64_encode($hasPrescriptionBill->id);
    $idEncryptedBill = Crypt::encrypt($base64BillId);
}

?>

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div id="error-message-container">
    <p id="error-message" class="myadmin-alert myadmin-alert-icon myadmin-alert-click alert-danger alerttop fadeOut"
        style="display: none;"></p>
</div>

<meta name="csrf-token" content="{{ csrf_token() }}">

<form method="POST" id="prescriptionBillingForm" action="{{ route('medicineBilling.store') }}"
    enctype="multipart/form-data">
    @csrf
    <section class="content">
        <div class=" row invoice-info">
            <div class=" col-sm-12 invoice-col mb-15">
                <div class="flexbox invoice-details px-1   no-margin">
                    <div>
                        <p class="mb-1"><b>Bill No: </b>
                            @if ($hasPrescriptionBill)
                                {{ $hasPrescriptionBill->bill_id }}
                            @endif
                        </p>

                        <p class="mb-0"><b>Generated at: </b>
                            {{-- {{ date('d/m/Y H:m:s') }} --}}
                            {{ date('d/m/Y h:i:s A') }}
                        </p>
                    </div>
                    <div>
                        <input type="hidden" value="{{ $idEncrypted }}" name="appointmentId" id="appointmentId">
                        <input type="hidden" value="{{ $appointment->patient_id }}" name="patientId">
                        <input type="hidden" name="medbillId" id="medbillId" value="{{ $idEncryptedBill }}">
                        <b>Appointment ID: </b> {{ $appointment->app_id }}
                    </div>
                    <div><b>Mobile No.: </b> {{ $appointment->patient->phone }}</div>
                    <div class="text-end">
                        <p class="mb-1"><b>Payment Due: </b> {{ date('d/m/Y') }}</p>
                        <p class="mb-0"><b>Generated by: </b> {{ Auth::user()->name }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 table-responsive-sm lh-1">
                <table class="table table-bordered caption-top text-center">
                    <caption class="pt-0">Prescription Details</caption>
                    <thead class="bg-dark">
                        <tr>
                            <th style="width: 5%;">#</th>
                            <th style="width:35%;">Medicine</th>
                            <th style="width:10%;">Dose</th>
                            <th style="width:10%;">Frequency</th>
                            <th style="width:10%;">Duration</th>
                            <th style="width:10%;">Quantity</th>
                            <th style="width:5%;" class="text-center">Status</th>
                            <th style="width:20%;" class="text-center">Rate
                                ({{ $clinicBasicDetails->currency }})
                            </th>
                        </tr>
                    </thead>
                    <tbody id="tablebody">
                        <?php $i = 0;
                        $paidAmount = '';
                        $modeOfPayment = '';
                        $gpayAmount = '';
                        $cashAmount = '';
                        $cardAmount = '';
                        $machineId = '';
                        $balanceGiven = ''; ?>
                        @foreach ($prescriptions as $prescription)
                            @php
                                $i++;
                                $isOutOfStock = $prescription->medicine->stock_status === 'Out of Stock';
                                $totalQuantity = $prescription->medicine->total_quantity;
                                $isChecked = false;
                                $quantityValue = '';
                                $rateValue = '';
                                $paidAmount = '';
                                $modeOfPayment = '';
                                $gpayAmount = '';
                                $cashAmount = '';
                                $cardAmount = '';
                                $machineId = '';
                                $balanceGiven = '';

                                // Check if prescription bill details contain this medicine
                                $billDetail = $prescriptionBillDetails->firstWhere(
                                    'medicine_id',
                                    $prescription->medicine->id,
                                );

                                if ($billDetail) {
                                    $isChecked = true;
                                    $quantityValue = $billDetail->quantity;
                                    $rateValue = $billDetail->rate;
                                }
                                if ($hasPrescriptionBill) {
                                    $paidAmount = $hasPrescriptionBill->amount_paid;
                                    $gpayAmount = $hasPrescriptionBill->gpay;
                                    $cashAmount = $hasPrescriptionBill->cash;
                                    $cardAmount = $hasPrescriptionBill->card;
                                    $machineId = $hasPrescriptionBill->card_pay_id;
                                    $balanceGiven = $hasPrescriptionBill->balance_given;
                                }
                            @endphp
                            <tr class="{{ $isOutOfStock ? 'bg-light text-muted' : '' }}">
                                <td>{{ $i }}</td>
                                <td class="text-start">
                                    <input type="checkbox" id="medicine_checkbox{{ $loop->index }}"
                                        name="medicine_checkbox[]" class="filled-in chk-col-success"
                                        value="{{ $prescription->medicine->id }}" {{ $isChecked ? 'checked' : '' }}
                                        data-price="{{ $prescription->medicine->med_price }}"
                                        {{ $isOutOfStock ? 'disabled' : '' }} />
                                    <label for="medicine_checkbox{{ $loop->index }}">
                                        {{ $prescription->medicine->med_name }}
                                    </label>
                                </td>
                                <td>
                                    <div class="input-group col-12">
                                        <input type="number" class="form-control text-center"
                                            id="duration{{ $loop->index }}" name="duration[]"
                                            aria-describedby="basic-addon2" value="{{ $prescription->dose }}"
                                            {{ $isOutOfStock ? 'disabled' : '' }} readonly>
                                        <div class="input-group-append">
                                            <span class="input-group-text"
                                                id="basic-addon2">{{ $prescription->dose_unit }}</span>
                                        </div>
                                    </div>
                                </td>

                                <th>{{ $prescription->dosage->dos_name }}</th>
                                <td>
                                    <div class="input-group col-12">
                                        <input type="number" class="form-control text-center"
                                            id="duration{{ $loop->index }}" name="duration[]"
                                            aria-describedby="basic-addon2" value="{{ $prescription->duration }}"
                                            {{ $isOutOfStock ? 'disabled' : '' }} readonly>
                                        <div class="input-group-append">
                                            <span class="input-group-text" id="basic-addon2">days</span>
                                        </div>
                                    </div>
                                </td>
                                <th>
                                    <input type="number" name="quantity[]" id="quantity{{ $loop->index }}"
                                        data-total-quantity="{{ $totalQuantity }}" class="form-control text-center"
                                        {{ $isOutOfStock ? 'disabled' : '' }} {{ $quantityValue ? 'readonly' : '' }}
                                        value="{{ $quantityValue }}">
                                    <span id="stock_message{{ $loop->index }}" class="text-danger"></span>
                                    <span id="quantity{{ $loop->index }}-error" class="text-danger"></span>
                                </th>
                                <td>
                                    {{-- {{ $prescription->medicine->stock_status }} --}}
                                    @if ($prescription->medicine->stock_status == 'In Stock')
                                        <span class="text-success" title="in stock"><i
                                                class="fa-solid fa-circle-check"></i></span>
                                    @else
                                        <span class="text-danger" title="out of stock"><i
                                                class="fa-solid fa-circle-xmark"></i></span>
                                    @endif
                                </td>
                                <td>
                                    <input type="hidden" id="unitcost{{ $loop->index }}" name="unitcost[]"
                                        value="{{ $prescription->medicine->med_price }}">
                                    <input type="text" class="form-control text-center" id="rate{{ $loop->index }}"
                                        name="rate[]" value="{{ $rateValue }}" aria-describedby="basic-addon2"
                                        {{ $isOutOfStock ? 'disabled' : '' }} readonly>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="7" class="text-end">Total</th>
                            <th><input type="text" class="form-control text-center" id="total" name="total"
                                    aria-describedby="basic-addon2" readonly>
                                <span class="text-danger" id="prescTotalError">
                                    @error('total')
                                        {{ $message }}
                                    @enderror
                                </span>
                            </th>
                        </tr>
                        <tr>
                            <th colspan="7" class="text-end">Tax</th>
                            <td><input type="hidden" class="form-control text-center" id="medtax" name="medtax"
                                    aria-describedby="basic-addon2" value="{{ $clinicBasicDetails->tax }}" readonly>
                                <label>{{ $clinicBasicDetails->tax }}%</label>
                                <span class="text-danger" id="prescTaxError">
                                    @error('medtax')
                                        {{ $message }}
                                    @enderror
                                </span>
                            </td>
                        </tr>
                        {{-- <tr> --}}
                        <tr class="bt-3 border-primary">
                            <td colspan="7" class="text-end">
                                <h3><b>Grand Total</b></h3>
                            </td>
                            <td>
                                <input type="text" class="form-control text-center" id="grandTotal"
                                    name="grandTotal" aria-describedby="basic-addon2" readonly>
                                <span class="text-danger" id="prescGrandTotalError">
                                    @error('grandTotal')
                                        {{ $message }}
                                    @enderror
                                </span>
                            </td>
                        </tr>
                        <tr>
                                
                            <td colspan="4" class="text-start">
                                <span class="text-bold me-2">Mode of Payment:</span>

                                <!-- Checkbox for Gpay -->
                                <input type="checkbox" class="filled-in chk-col-success" id="medmode_of_payment_gpay"
                                    name="medmode_of_payment[]" value="gpay" <?php if ($gpayAmount >0) { ?> checked
                                    <?php } ?>>
                                <label class="form-check-label me-2" for="medmode_of_payment_gpay">Gpay</label>
                                <input type="text" name="medgpay" id="medgpay" class="form-control  w-100 "
                                    style="display: none;" value="{{ $gpayAmount }}">
                                &nbsp;
                                <!-- Checkbox for Cash -->
                                <input type="checkbox" class="filled-in chk-col-success" id="medmode_of_payment_cash"
                                    name="medmode_of_payment[]" value="cash" <?php if ($cashAmount >0) { ?> checked
                                    <?php } ?>>
                                <label class="form-check-label me-2" for="medmode_of_payment_cash">Cash</label>
                                <input type="text" name="medcash" id="medcash" class="form-control  w-100"
                                    style="display: none;" value="{{ $cashAmount }}">
                                &nbsp;
                                <!-- Checkbox for Card -->
                                <input type="checkbox" class="filled-in chk-col-success" id="medmode_of_payment_card"
                                    name="medmode_of_payment[]" value="card" <?php if ($cardAmount >0) { ?> checked
                                    <?php } ?>>
                                <label class="form-check-label me-2" for="medmode_of_payment_card">Card</label>
                                <input type="text" name="medcard" id="medcard" class="form-control  w-100 "
                                    style="display: none;" value="{{ $cardAmount }}">
                                <select class="ms-2 form-select w-150" id="medmachine" name="medmachine"
                                    style="display: none;">
                                    <option value="">Select Machine</option>
                                    @foreach ($cardPay as $machine)
                                        <option value="{{ $machine->id }}"
                                            {{ $machine->id == $machineId ? 'selected' : '' }}>
                                            {{ $machine->card_name }}</option>
                                    @endforeach
                                </select>
                                <span class="text-danger" id="prescModePaymentError">
                                    @error('medmode_of_payment')
                                        {{ $message }}
                                    @enderror
                                </span>
                            </td>

                            <td colspan="3" class="text-end ">Paid Amount</td>
                            <td>
                                <input type="text" name="medamountPaid" id="medamountPaid"
                                    {{ $paidAmount ? 'readonly' : '' }} class="form-control text-center"
                                    value="{{ $paidAmount }}" required readonly>
                                <span id="prescAmountPaidError" class="error-message text-danger">
                                    @error('medamountPaid')
                                        {{ $message }}
                                    @enderror
                                </span>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="4" class="text-start">
                                <input type="checkbox" name="medbalance_given" id="medbalance_given"
                                    class="filled-in chk-col-success" <?php if ($balanceGiven >0) { ?> checked <?php } ?>>
                                <label class="form-check-label" for="medbalance_given">Balance Given</label>
                                <span class="error-message text-danger" id="prescCheckError"></span>
                            </td>
                            <td colspan="3" class="text-end">Balance to Give Back</td>
                            <td><input type="text" name="medbalanceToGiveBack" id="medbalanceToGiveBack"
                                    class="form-control text-center" readonly>
                                <span class="text-danger" id="prescBalanceToGiveBackError">
                                    @error('medbalanceToGiveBack')
                                        {{ $message }}
                                    @enderror
                                </span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row text-end py-3">
            <div class="col-12">
                <?php if (!$hasPrescriptionBill) { 
                    if (Auth::user()->can('bill payment')) {?>
                <button type="button" class="btn btn-success pull-right" name="prescSubmitPayment"
                    id="prescSubmitPayment"><i class="fa fa-credit-card"></i>
                    Submit Payment
                </button>
                <?php  } } else { ?>
                <button type="button" class="btn btn-warning pull-right" name="prescPrintPayment"
                    id="prescPrintPayment"><i class="fa fa-print"></i>
                    Print Receipt
                </button>
                <?php } ?>
            </div>
        </div>
    </section>
</form>

<script>
    var prescriptionReceiptRoute = "{{ route('medicineBilling.paymentReceipt') }}";
    var prescriptionBillingRoute = "{{ route('billing') }}";
</script>
<script src="{{ asset('js/prescription_billing.js') }}"></script>
